### PR TITLE
Add the latest version in documentation

### PR DESCRIPTION
**Pull request by mohsenkashi**

### CODE REVIEW

**Comment by nafg** [comment]
Hi, thanks for the PR.

However, it seems 0.8.0 still uses Slick 3.3.2. That said, it should be binary compatible which means that 3.3.3 should work fine even with earlier versions. I guess the top row should just be changed to 0.8.0.

**Comment by mohsenkashi** [comment]
See #97 
It's merged in 0.8.0

**Comment by nafg** [comment]
Why do you think that?

See https://github.com/nafg/slick-migration-api/blob/v0.8.0/build.sbt

**Comment by mohsenkashi** [comment]
Fixed.
By clicking on release, github compares the version with the master branch. I misunderstood that it's a comparison with the previous release!

**Comment by nafg** [comment]
Thanks. Can you remove the 0.7.0 row?

**Comment by mohsenkashi** [comment]
> Thanks. Can you remove the 0.7.0 row?

Done

**Comment by nafg** [comment]
Thanks!

**Pull request merged**
