### PR TITLE
Support for Slick 3.0.x

### PR DESCRIPTION
**Pull request by Romastyi**
Hello. I was inspired by your project and had added to it the Slick 3.0.x API support.

### CODE REVIEW

**Comment by nafg** [comment]
Thanks!!

Can I just request that you remove formatting changes, so the only changes are those which are necessary for the PR title. Any other changes could go in other PRs if appropriate. Thanks.

**Comment by Romastyi** [comment]
No problem. It's done!

**Comment by driverpt** [comment]
@nafg , you have any ETA on this ?

**Comment by nafg** [comment]
Sorry guys. I hope today (started last night but something came up).

**Comment by nafg** [comment]
Merged as 1047285a6bc6af0ca40af233796c9d720b0eac12

**Comment by nafg** [comment]
It's now available on jcenter for slick 3.0.3 as `"io.github.nafg" %% "slick-migration-api" % "0.2.0"`

**Comment by nafg** [comment]
Working on 3.1.1...

**Comment by nafg** [comment]
0.2.1 for slick 3.1.1 on its way...

**Comment by nafg** [comment]
https://travis-ci.org/nafg/slick-migration-api/builds/135731561

**Comment by nafg** [comment]
Fixes #6

**Pull request closed without merging**
