### PR TITLE
Wip: support Slick 3.2 and Scala 2.12

### PR DESCRIPTION
**Pull request by nafg**

### CODE REVIEW

**Comment by nafg** [comment]
Review by @cvogt

**Comment by nafg** [comment]
TBD: how to version the release (if I just bump the version number, what happens if I want an update for an earlier slick?)

**Comment by lastland** [comment]
Right now we manage this in Scala-Forklift by having two versions (in two branches): `x.x.x` for Slick 3.1, and `x.x.x-slick3.2` for Slick 3.2.

**Comment by nafg** [comment]
That won't work well with version ordering.

**Comment by cvogt** [comment]
LGTM!

**Comment by lastland** [comment]
How about adding `-slick3.2` to the artifact id then?

**Pull request merged**
